# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
        DISPLAY: :99.0

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install 
    - run: npm run build
    # - run: sudo apt-get install xvfb
    # - run: xvfb-run --auto-servernum npm run jest
    # - run: npm run lint
    - uses: actions/upload-pages-artifact@v3
      with:
        path: build
  publish:
    needs: build
    uses: ./.github/workflows/npm-publish-github.yml